[package]
name = "benaloh-cryptosystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-bigint = "0.5.3"
crypto-primes = "0.5.0"
digest = "0.10.7"
rand = "0.8.5"
sha3 = "0.10.8"
